### ISSUE TITLE
How is the trace file generated?

### ISSUE THREAD

**Issue by yuang-chen** [faldupriyank/grasp#1]
Dear Faldu,

I would like to try your code on different datasets. But I got stuck in the very beginning point, because I cannot find instructions/codes relating to the generation of traces. 

Can you please elaborate how those `trace ` files in the datasets folder were generated?  
So that I can re-do your experiment with other graph datasets.

Best Regards,
YuAng

**Comment by faldupriyank** [comment]
Dear YuAng,

In the paper, most of the evaluation was done through full simulations of ROI for different graph workloads using Sniper, and not through trace-based simulation. Unfortunately, due to licesnse issues, we are unable to share the code changes. Instead, I have shared the GRASP implementation for a simple cache simulator for refernce only. **Ideally, one should use this implementation and integrate it into some performance simulator of their choice (e.g., Sniper, GEM5, Zsim, Flexus etc), rather than using the provided simulator due to the following reason mentioned in the README.** 

> Simulator is very simple, and assumes that all addresses are memory read. Simulator provides a first order effect of various policies on cache efficiency. However, it may not provide accurate results for write-dominated applications.

If you still would like to use the provided simulator to understand the first order effects of various cache replacement policies, you will need to generate the trace files as follows.

The file should contain a header in the begining containing region information as explained in the `read_file` function of the  `grasp/trace-based-simulators/cache.h` file. The header should be followed by 64-bit virtual addresses. While the file only provides a function to read a header and a list of addresses, it can be trivially extended with a similar write_file function to write a header followed by virtual addresses.

One thing to note is that the trace should only contain the list of addresses that miss in L2 cache as the simulator is expected to simulate LLC accesses. One way to generate these addresses is by using a PIN tool that implements 2-level caches. When application is attached to this PIN tool, it will recieve all application memory addresses, which would be propgated to both cache levels based on thier replacement policies and cache hits/misses. Only application addresses that miss in L2 should be dumped to an external trace file.
